[package]
name = "xlsxfin"
version = "0.1.0"
authors = ["abetomo <abe@enzou.tokyo>"]
description = "Excel Financial functions."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
